name: Continuous Integration

on:
  push:
    branches: [main]

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: false
          components: rustfmt

      - name: Build
        run: cargo build --workspace --all-features

      - name: Run tests
        run: cargo test --workspace --all-features

      - name: Run clippy
        run: cargo clippy --workspace --examples --tests --all-features

      - name: Check formatting
        run: cargo +nightly fmt -- --check

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Check all feature combinations
        run: cargo hack check --workspace --feature-powerset --no-dev-deps --depth 2
