name: Continuous Integration

on:
  push:
    branches: [main]

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Build
        run: cargo +stable build --workspace --all-features

      - name: Build WASM
        run: cargo +stable rustc --target wasm32-unknown-unknown --all-features --crate-type=cdylib

      - name: Run tests
        run: cargo +stable test --workspace --all-features

      - name: Run clippy
        run: cargo +stable clippy --workspace --examples --tests --all-features

      - name: Check formatting
        run: cargo +nightly fmt -- --check

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Check all feature combinations
        run: cargo +stable hack check --workspace --feature-powerset --no-dev-deps --depth 2
